### ISSUE TITLE
string numbers should be quoted

### ISSUE THREAD

**Issue by bj0** [aaubry/YamlDotNet#33] opened 2013-06-03 21:56 UTC
You get the same result if you serialize 5 or "5" or 5.0.  As a result, type information is lost:

```
var sw = new StringWriter();
(new Serializer()).Serialize(sw, "5");
(new Serializer()).Serialize(sw, 5);
(new Serializer()).Serialize(sw, 5.0);
sw.ToString().Dump("result"); // output: "5\n...\n5\n...\n5\n..."
```

Since the result can be explicitly deserialized into int, string, or double it's not a serious bug.

I'm not even sure what the yaml spec says on the issue, as I usually just see what the PyYaml implementation does:

```
>>> import yaml
>>> yaml.dump(1)
'1\n...\n'
>>> yaml.dump(1.0)
'1.0\n...\n'
>>> yaml.dump('1')
"'1'\n"
```

Anyway, great work on the library so far, the last release fixed a bug I was having trouble with :)

**Comment by Untit1ed** [comment] 2017-01-26 00:26
Any progress on this? `{"version": "2.0"}` is getting converted to `- version: 2.0`

**Comment by gabriel-samfira** [comment] 2018-12-21 14:08
I am also curious about progress on this. The problem is that not all strings should be serialized as ```Plain``` strings. This adds ambiguity. For example:

```powershell
$builder = [YamlDotNet.Serialization.SerializerBuilder]::new()
$serializer = $builder.Build()

$obj = @{"IAmAString" = "200"; "IAmAnInt" = 200}
$serializer.Serialize($obj)
```

which outputs:

```yaml
IAmAString: 200
IAmAnInt: 200
```

When you deserialize this, you loose the type. This is why the Python yaml module, adds single quotes around values that might cause ambiguity.

I think this could be fixed here:

https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Serialization/EventEmitters/TypeAssigningEventEmitter.cs#L83

By testing if the value can be cast to any type other than string, and set:

```
eventInfo.IsPlainImplicit = false;
eventInfo.IsQuotedImplicit = true;
```

**Comment by gabriel-samfira** [comment] 2018-12-21 21:37
So, using something like this:

```diff
diff --git a/YamlDotNet/Serialization/EventEmitters/TypeAssigningEventEmitter.cs b/YamlDotNet/Serialization/EventEmitters/TypeAssigningEventEmitter.cs
index dae028e..d78aff5 100644
--- a/YamlDotNet/Serialization/EventEmitters/TypeAssigningEventEmitter.cs
+++ b/YamlDotNet/Serialization/EventEmitters/TypeAssigningEventEmitter.cs
@@ -81,6 +81,21 @@ namespace YamlDotNet.Serialization.EventEmitters
                     break;
 
                 case TypeCode.String:
+                    decimal dec;
+                    int number;
+                    float flt;
+                    long lng;
+                    double dbl;
+                    var val = eventInfo.Source.Value.ToString();
+                    if (Int32.TryParse(val, out number) ||
+                        Int64.TryParse(val, out lng) ||
+                        Double.TryParse(val, out dbl) ||
+                        Decimal.TryParse(val, out dec) ||
+                        float.TryParse(val, out flt))
+                    {
+                        eventInfo.Style = ScalarStyle.DoubleQuoted;
+                    }
+                    goto case TypeCode.Char;
                 case TypeCode.Char:
                     eventInfo.Tag = "tag:yaml.org,2002:str";
                     eventInfo.RenderedValue = eventInfo.Source.Value.ToString();
@@ -146,4 +161,4 @@ namespace YamlDotNet.Serialization.EventEmitters
             }
         }
     }
-}
\ No newline at end of file
+}

```

Results in:

```powershell
$builder = [YamlDotNet.Serialization.SerializerBuilder]::new()
$serializer = $builder.Build()
$obj = @{
    "IAmAString" = "200"
    "IAmAnInt" = 200
    "11" = "KeyAsIntAndShouldBeDisambiguated"
    "1sa1" = "JustAStringStartingWithANumber"
}
$serializer.Serialize($obj)                                                                                                           
IAmAnInt: 200
IAmAString: "200"
"11": KeyAsIntAndShouldBeDisambiguated
1sa1: JustAStringStartingWithANumber
```

Which uses quotes around values that are at risk to loose their type when serialized and deserialized.

**Comment by ridhoq** [comment] 2020-04-19 00:02
Just checking in on the progress of this. It looks like @gabriel-samfira has fixed this downstream in the following PR: https://github.com/cloudbase/powershell-yaml/pull/41/files#diff-e4c14acd05e286e165f6b75e7a30d165. Is it possible to bring this change (or something similar) upstream in this library?

**Comment by Roadrunner67** [comment] 2020-04-21 13:11
@aaubry I noticed you accepted my PR #477, are you up to a version release soon?
What do you need to include this fix from @gabriel-samfira ?

**Comment by aaubry** [comment] 2020-04-21 14:56
@Roadrunner67 I'll do a release today. Regarding the fix, I don't think it should be included because I don't think that it is correct. The YAML language uses tags to represent types. Whether a scalar is plain or quoted is a presentation detail. The [spec](https://yaml.org/spec/1.2/spec.html#id2764652) states that two scalars are equal if they have the same tag and content, regardless of their style.

Nevertheless, if someone wants @gabriel-samfira 's behaviour, it is just a matter of registering a implementation of [`IEventEmitter`](https://github.com/aaubry/YamlDotNet/wiki/Serialization.Serializer#witheventemitter). There's no need to change the existing code.

**Comment by gabriel-samfira** [comment] 2020-04-21 15:14
> Nevertheless, if someone wants @gabriel-samfira 's behaviour, it is just a matter of registering a implementation of [`IEventEmitter`](https://github.com/aaubry/YamlDotNet/wiki/Serialization.Serializer#witheventemitter)

That is actually how we implemented it in the end in ```powershell-yaml```. At least for now. Tags should be the long term solution. Just need to find the time to do it.

@aaubry not sure if I ever mentioned this before, but thanks for all your work!

**Comment by aaubry** [comment] 2020-04-21 15:17
Thanks @gabriel-samfira, you're welcome!

**Comment by Ronan-Lenor** [comment] 2020-07-20 14:26
is it normal that it don't work in 8.1.2?
do i have to wait the version 8.1.3?

for the moment i still use something like that:
    key: !!int 1000

**Comment by Jossec101** [comment] 2021-06-23 16:53
What about this issue? In my case, I am using converting JSON-based docker compose to yaml:

Example:
```json
{"version": "3.4", "services": {"hello_world": {"image": "ubuntu", "command": ["/bin/echo", "Hello world"]}}}
````

Which after using YamlDotnet results in:

```yaml
version: 3.4
services:
  hello_world:
    image: ubuntu
    command:
    - /bin/echo
    - Hello world
```

As you can see, version string is lost, while if you check the version string in the ExpandoObject is still there:

![2021-06-23_18-49-55](https://user-images.githubusercontent.com/53834183/123137121-f30cab80-d453-11eb-84ca-7f9cf3b666d0.jpg)


My code:

```cs
var expConverter = new ExpandoObjectConverter();
dynamic deserializedObject = JsonConvert.DeserializeObject<ExpandoObject>(rawText, expConverter);

var serializer = new Serializer();
var yaml = (string)serializer.Serialize(deserializedObject);
```

**Comment by EdwardCooke** [comment] 2022-07-16 04:09
I know this is pretty old, but it will be resolved in the next release so I'm closing this.

**Closed by EdwardCooke** 2022-07-16 04:09 UTC

**Comment by Mrgaton** [comment] 2023-01-26 17:51
Please fix it

**Comment by EdwardCooke** [comment] 2023-01-26 21:19
It’s actually released. On the serializer builder call with quoting necessary strings.

**Comment by Mrgaton** [comment] 2023-01-26 23:55
> It’s actually released. On the serializer builder call with quoting necessary strings.

It highlights everything except the strings

**Comment by edwardcookemacu** [comment] 2023-01-27 01:55
This works, quoting string when they are numbers

```c#
using YamlDotNet.Serialization;

var test = new { Item = "123" };

var serializer = new SerializerBuilder()
    .WithQuotingNecessaryStrings()
    .Build();
var actual = serializer.Serialize(test);

Console.WriteLine(actual);
```
Results in:
```
Item: "123"
```

**Comment by Mrgaton** [comment] 2023-01-27 12:04
yes but i dont want to quote numbers or bools I want to quote strings

**Comment by EdwardCooke** [comment] 2023-01-27 15:32
Currently you can use the yamlmember attribute to specify you want double or single quotes.

Currently there is no feature for defaulting to using quotes. Wouldn’t be  hard to do though. If that is what you are looking for, open a new issue.
