### ISSUE TITLE
Exception scanning block scalar with leading tabs

### ISSUE THREAD

**Issue by J-Boyd** [aaubry/YamlDotNet#86] opened 2014-01-19 23:12 UTC
According to the yaml spec, literal style block scalars should be able to contain tabs. When trying to parse a yaml document with a format like this:

```yaml
output: |
  \tline beggining with tab
  another line
```

Where the '\t' is a tab (preceded by a valid indentation of two spaces).

Currently, I get the following error when loading a yaml stream with a block scalar as above:
"While scanning a block scalar, find a tab character where an intendation space is expected."

I don't think it should be expecting an indentation space at this point.

**Comment by aaubry** [comment] 2016-08-30 22:49
Closing this because the issue is too old, amd probably no longer exists. Please open a new issue if you still encounter this bug.

**Closed by aaubry** 2016-08-30 22:49 UTC
