### ISSUE TITLE
Alias support in JSON

### ISSUE THREAD

**Issue by dbpiper** [aaubry/YamlDotNet#354] opened 2018-10-03 17:41 UTC
Currently when attempting to serialize into JSON with JsonCompatible on SerializerBuilder an exception is thrown when an alias is encountered. With the message "Aliases are not supported in JSON". I have used several other YAML to JSON serializers that support this including: Json.NET and the Python json package. I haven't investigated further, but I'd imagine that they simply achieve alias at least rudimentary alias support by simply duplicating the entries or some similar scheme.

The purpose of this issue is to track the support of Aliasing in serializing to JSON.

If there are no plans to support it, than this issue can at least hold that information as well.

**Comment by aaubry** [comment] 2018-10-03 18:01
This looks like a bug. Have you tried calling `DisableAliases()` on the SerializerBuilder to see if the problem persists ?

**Comment by OleksiiChornousov** [comment] 2019-06-05 14:30
I am also getting error "Aliases are not supported in JSON" when using nswag generator tool. 

The call stack for the reference:
```
System.NotSupportedException: Aliases are not supported in JSON
   at YamlDotNet.Serialization.EventEmitters.JsonEventEmitter.Emit(AliasEventInfo eventInfo, IEmitter emitter)
   at YamlDotNet.Serialization.ObjectGraphVisitors.AnchorAssigningObjectGraphVisitor.Enter(IObjectDescriptor value, IEmitter context)
   at YamlDotNet.Serialization.ObjectGraphVisitors.ChainedObjectGraphVisitor.Enter(IObjectDescriptor value, IEmitter context)
   at YamlDotNet.Serialization.ObjectGraphVisitors.CustomSerializationObjectGraphVisitor.Enter(IObjectDescriptor value, IEmitter context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.Traverse[TContext](IObjectDescriptor value, IObjectGraphVisitor`1 visitor, Int32 currentDepth, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.TraverseDictionary[TContext](IObjectDescriptor dictionary, IObjectGraphVisitor`1 visitor, Int32 currentDepth, Type keyType, Type valueType, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.TraverseObject[TContext](IObjectDescriptor value, IObjectGraphVisitor`1 visitor, Int32 currentDepth, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.Traverse[TContext](IObjectDescriptor value, IObjectGraphVisitor`1 visitor, Int32 currentDepth, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.TraverseDictionary[TContext](IObjectDescriptor dictionary, IObjectGraphVisitor`1 visitor, Int32 currentDepth, Type keyType, Type valueType, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.TraverseObject[TContext](IObjectDescriptor value, IObjectGraphVisitor`1 visitor, Int32 currentDepth, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.Traverse[TContext](IObjectDescriptor value, IObjectGraphVisitor`1 visitor, Int32 currentDepth, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.TraverseDictionary[TContext](IObjectDescriptor dictionary, IObjectGraphVisitor`1 visitor, Int32 currentDepth, Type keyType, Type valueType, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.TraverseObject[TContext](IObjectDescriptor value, IObjectGraphVisitor`1 visitor, Int32 currentDepth, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.Traverse[TContext](IObjectDescriptor value, IObjectGraphVisitor`1 visitor, Int32 currentDepth, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.TraverseDictionary[TContext](IObjectDescriptor dictionary, IObjectGraphVisitor`1 visitor, Int32 currentDepth, Type keyType, Type valueType, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.TraverseObject[TContext](IObjectDescriptor value, IObjectGraphVisitor`1 visitor, Int32 currentDepth, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.Traverse[TContext](IObjectDescriptor value, IObjectGraphVisitor`1 visitor, Int32 currentDepth, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.TraverseDictionary[TContext](IObjectDescriptor dictionary, IObjectGraphVisitor`1 visitor, Int32 currentDepth, Type keyType, Type valueType, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.TraverseObject[TContext](IObjectDescriptor value, IObjectGraphVisitor`1 visitor, Int32 currentDepth, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.Traverse[TContext](IObjectDescriptor value, IObjectGraphVisitor`1 visitor, Int32 currentDepth, TContext context)
   at YamlDotNet.Serialization.ObjectGraphTraversalStrategies.FullObjectGraphTraversalStrategy.YamlDotNet.Serialization.IObjectGraphTraversalStrategy.Traverse[TContext](IObjectDescriptor graph, IObjectGraphVisitor`1 visitor, TContext context)
   at YamlDotNet.Serialization.SerializerBuilder.ValueSerializer.SerializeValue(IEmitter emitter, Object value, Type type)
   at YamlDotNet.Serialization.Serializer.EmitDocument(IEmitter emitter, Object graph, Type type)
   at YamlDotNet.Serialization.Serializer.Serialize(IEmitter emitter, Object graph)
   at YamlDotNet.Serialization.Serializer.Serialize(TextWriter writer, Object graph)
   at YamlDotNet.Serialization.Serializer.Serialize(Object graph)
   at NSwag.SwaggerYamlDocument.FromYamlAsync(String data, String documentPath, SchemaType expectedSchemaType, Func`2 referenceResolverFactory) in C:\projects\nswag\src\NSwag.Core.Yaml\SwaggerYamlDocument.cs:line 63
   at NSwag.SwaggerYamlDocument.FromFileAsync(String filePath) in C:\projects\nswag\src\NSwag.Core.Yaml\SwaggerYamlDocument.cs:line 91
   at NSwag.Commands.OutputCommandBase.ReadSwaggerDocumentAsync(String input) in C:\projects\nswag\src\NSwag.Commands\Commands\OutputCommandBase.cs:line 43
   at NSwag.Commands.InputOutputCommandBase.GetInputSwaggerDocument() in C:\projects\nswag\src\NSwag.Commands\Commands\InputOutputCommandBase.cs:line 44
   at NSwag.Commands.CodeGeneration.SwaggerToTypeScriptClientCommand.<RunAsync>b__138_0() in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\SwaggerToTypeScriptClientCommand.cs:line 357
   at NSwag.Commands.CodeGeneration.SwaggerToTypeScriptClientCommand.RunAsync() in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\SwaggerToTypeScriptClientCommand.cs:line 350
   at NSwag.Commands.CodeGeneration.SwaggerToTypeScriptClientCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\CodeGeneration\SwaggerToTypeScriptClientCommand.cs:line 343
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 54
```

**Comment by aaubry** [comment] 2019-06-05 18:06
Have you tried calling DisableAliases() on the SerializerBuilder to see if the problem persists ?

**Comment by OleksiiChornousov** [comment] 2019-06-06 09:22
The problem is I am not using the YamlDotNet directly, but the nswag tool does - https://github.com/RicoSuter/NSwag.

**Comment by aaubry** [comment] 2019-09-25 22:38
I will close this issue as there has been no feedback. If the problem occurs with the nswag tool, then someone need to check what this tool is doing and provide more information. Thanks

**Closed by aaubry** 2019-09-25 22:38 UTC
