### ISSUE TITLE
Serialize enum object is failed

### ISSUE THREAD

**Issue by Takahisa-Ishikawa** [aaubry/YamlDotNet#268] opened 2017-07-13 06:12 UTC
Serialize enum object  fails with the following code. 
Can you tell me who knows the solution?

--- Code ---
    public enum MyEnum
    {
        One, Two,
    }

    public class MyClass
    {
        public MyEnum One { get; set; } = MyEnum.One;
        public MyEnum Two { get; set; } = MyEnum.Two;
    }

    [TestClass()]
    public class MyTestClass
    {
        [TestMethod]
        public void MyTestMethod()
        {
            var inst = new MyClass
            {
                One = MyEnum.Two,
                Two = MyEnum.One,
            };

            var yamlText = new Serializer().Serialize(inst);
            Trace.WriteLine(yamlText);
            Assert.AreEqual(@"One: Two
Two: One", yamlText);
        }
    }

--- Error ---
Test Name:	MyTestMethod
Test Outcome:	Failed

Result Message:	
Assert.AreEqual failed. Expected:<One: Two
Two: One>. Actual:<One: Two
>.

**Comment by aaubry** [comment] 2017-07-13 13:06
Since `MyEnum.One` is the default value of the enum, you need to specify that default values must be emitted when configuring the serializer:
```c#
var serializer = new SerializerBuilder()
    .EmitDefaults()
    .Build();
```

**Comment by aaubry** [comment] 2017-07-13 13:06
Closing because this is a duplicate of #251

**Closed by aaubry** 2017-07-13 13:06 UTC

**Comment by Takahisa-Ishikawa** [comment] 2017-07-18 02:29
Thank you for your kindness.

**Comment by aaubry** [comment] 2019-08-15 00:29
I have opened issue #427 that is related to your question. Feel free to join the discussion and provide any feedback that might be relevant.
