### ISSUE TITLE
Property 'access-points' not found on type ...

### ISSUE THREAD

**Issue by jiangzhuangxiansheng** [aaubry/YamlDotNet#860] opened 2023-10-26 11:38 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![image](https://github.com/aaubry/YamlDotNet/assets/33273148/1fd53d72-dddb-47af-a874-65070f422b9f)
![image](https://github.com/aaubry/YamlDotNet/assets/33273148/f82c24e0-687a-454e-94e1-ff9c660ebdc5)
![image](https://github.com/aaubry/YamlDotNet/assets/33273148/bfb92684-a964-457b-8f6f-4dd33e237855)

It's not clear why this is happening
**Describe alternatives you've considered**

**Additional context**

**Comment by EdwardCooke** [comment] 2023-10-26 13:11
My guess is passing in the naming convention when you build the deserializer. Try removing that and see what happens. If you still get an error let me know and I’ll take a deeper look. Also. Copy paste the yaml and code I really dont want to retype all of that to reproduce the problem. Wrap it in new lines with 3 back ticks.  It's these ```

**Comment by EdwardCooke** [comment] 2023-10-26 13:11
And what version of the library are you using?

**Comment by jiangzhuangxiansheng** [comment] 2023-10-27 03:07
I set ApplyNamingConventions = false to parse correctly

**Comment by EdwardCooke** [comment] 2023-11-14 15:50
Since you found a solution, I'm closing this.

**Closed by EdwardCooke** 2023-11-14 15:50 UTC
