### ISSUE TITLE
Serialize a 0 int value

### ISSUE THREAD

**Issue by ranxian** [aaubry/YamlDotNet#258] opened 2017-05-15 00:45 UTC
I tried to serialize
```
class A {
  public int number {get; set;} = 0;
}
```
when `number` is 0, there is nothing serialized. I was expecting something like
```
number: 0
```

**Comment by Bond-009** [comment] 2017-05-15 05:08
Default values are not emitted unless you call .EmitDefaults() on the SerializerBuilder.

**Comment by aaubry** [comment] 2017-07-13 13:07
Closing because this is a duplicate of #251

**Closed by aaubry** 2017-07-13 13:07 UTC

**Comment by aaubry** [comment] 2019-08-15 00:29
I have opened issue #427 that is related to your question. Feel free to join the discussion and provide any feedback that might be relevant.
