### ISSUE TITLE
Deserializing multiple documents in one file PLUS TAGS

### ISSUE THREAD

**Issue by derFunk** [aaubry/YamlDotNet#140] opened 2015-09-16 17:10 UTC
Hi,

it seems that the combination of having multiple documents in a single file and using tags for all the nested documents does not work.
This is the case for serialized scene files from Unity.

The reason obviously is that the %TAG definition is only read once for the first nested document, but not for the following ones, resulting in a `While parsing a node, find undefined tag handle.` exception.

Testfile:
```yaml
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!29 &1
SceneSettings:
  m_ObjectHideFlags: 0
--- !u!104 &2
RenderSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 6
  m_Fog: 0
--- !u!127 &3
LevelGameManager:
  m_ObjectHideFlags: 0
--- !u!157 &4
LightmapSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 5
```

I implemented a NodeTypeResolver to resolve the Unity integer class mappings.
Source code here: https://gist.github.com/derFunk/795d7a366627d59e0dbd

(You'd need UnityEngine.dll referenced in your test project which you can get from the [free Unity download](http://beta.unity3d.com/download/f0a33a6ef422/Windows64EditorInstaller/UnitySetup64-5.1.3p3.exe), and you don't even have to install Unity - just open the installer exe in 7zip and grab it from `$_OUTDIR\Managed\UnityEngine.dll` - easy.)

My test code:
```csharp
void Start(string searchFolder)
{
	var deserializer = new Deserializer();

	// put my resolver first!
	// this is only necessary because another bug:
	// TypeNameInTagNodeTypeResolver needs an update to
	// return false when "Type.GetType" throws an exception, in order to pass on the
	// resolving to the next resolver
	var oldResolvers = new INodeTypeResolver[deserializer.TypeResolvers.Count];
	deserializer.TypeResolvers.CopyTo(oldResolvers, 0);
	deserializer.TypeResolvers.Clear(); // copies entries to oldResolvers!
	deserializer.TypeResolvers.Add(new UnityNodeTypeResolver());
	foreach (var nodeTypeResolver in oldResolvers)
		deserializer.TypeResolvers.Add(nodeTypeResolver);

	try
	{
		var yamlText = File.ReadAllText("scenefile.unity");
		var reader = new EventReader(new Parser(new StringReader(yamlText)));
		
		// important for reading multiple documents in one file (stream)
		// see also https://github.com/aaubry/YamlDotNet/issues/12
		reader.Allow<StreamStart>();

		while (!reader.Accept<StreamEnd>())
		{
			// first test deserialization
			var obj = deserializer.Deserialize(reader);
		}
		// do something
	}
	catch (Exception e)
	{
		Console.Writeline(file + ": " + e);
		Environment.Exit(1);
	}
}
```

**Comment by derFunk** [comment] 2015-09-17 09:34
May be related to this PR: https://github.com/aaubry/YamlDotNet/pull/102

**Comment by derFunk** [comment] 2015-09-17 15:34
Meta Info: Unity files still are not parseable if they contain the "stripped" keyword after the document boundary marker - see also http://forum.unity3d.com/threads/scene-files-invalid-yaml.355653/.

Not sure if that's a violation of the specification and thus invalid YAML documents Unity produces.

**Comment by derFunk** [comment] 2015-09-21 13:15
If anybody has feedback on validity of the Unity scene file format, let me know!

Is this valid YAML?
```yaml
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!4 &41387171 stripped
Transform:
m_PrefabParentObject: {fileID: 476688, guid: d1cbe4ee1e40dbb46aa458321c1b846a, type: 2}
m_PrefabInternal: {fileID: 41387170}
```

**Comment by meng-hui** [comment] 2015-09-30 08:14
I ran into this as well. The problem seems to be with the word `stripped`. By removing it, I can load a `YamlStream` of a Unity scene file. In my limited test, Unity was able to load the scene file with the missing stripped word as well. As far as I know, this is caused by modifications to prefabs saved into scene.

According to the [Yaml Spec](http://www.yaml.org/spec/1.2/spec.html) 6.9.2, it seems to be valid YAML, but I'm not too sure myself too.

**Comment by aaubry** [comment] 2016-04-07 14:18
My analysis is that this is invalid according to the YAML specification. When parsing the document, the parser will find the following elements:

1. A tag - "!u!4"
1. An anchor - "&67580648"
1. A scalar - "stripped"
1. A mapping whose key is "Transform"
1. The remainder of the mapping

It is not valid for a scalar to be followed by a mapping. I also tested with other YAML parsers and all of them reject this syntax, so I believe that it is indeed invalid. I tried to see if it would be possible to intercept the "stripped" token, but I found that it would require to extend the scanner and parser in ways that are not currently possible.

I searched the Unity documentation but could not find any mention of this "stripped" keyword. Do you know what it means?

**Comment by aaubry** [comment] 2016-04-07 14:54
Actually, my analysis is wrong. When parsing the document, the parser will find the following elements:

1. A tag - "!u!4"
1. An anchor - "&67580648"
1. A scalar - "stripped\nTransform"
1. The remainder of the mapping

So the "stripped" word becomes part of the key of the mapping, but because it is multi-line, it cannot be used as a key in a block context. Because of that, we cannot easily make the scanner ignore the "stripped" part.

**Comment by steinbitglis** [comment] 2016-04-08 17:24
Is it a flow node? http://www.yaml.org/spec/1.1/#flow style/syntax

**Comment by msklywenn** [comment] 2016-06-13 15:55
Valid or not, would it be possible to have support for parsing such files ? I'd like to work on a tool to merge unity scenes and this is the first gate to pass...
I tried running through the code to make the modification myself but this looks like quite tricky to add without a bigger knowledge of the codebase. Is there any text explaining how the parser works ? That could help.

YamlDotNet unrelated: does anybody reading this page know what the hell is that "stripped" keyword doing here in the first place ? :)

**Comment by aaubry** [comment] 2016-06-13 16:30
The first component that would require modification to support this would be the scanner. Its job is to take a stream of characters and produce a stream of tokens. It would probably need to return a new token type when encountering the "stripped" word. The parser would then also need to be modified to cope with the new token, but without knowing the meaning of the "stripped" keyword, it is unclear what should be done with it.

**Comment by derFunk** [comment] 2016-06-13 18:08
@msklywenn Are you aware of the official scene merger tool from Unity? Sounds very much like you want to do the same: http://docs.unity3d.com/Manual/SmartMerge.html

**Comment by msklywenn** [comment] 2016-06-13 18:16
Nope, I already use it and it's faaaaaaaaar from perfect. It helps, but it's not enough. Where it fails to merge, it relies on a regular text merge tool that is of course completely unaware of the multi-document structure of the file and it's a mess.

**Comment by aaubry** [comment] 2016-08-30 23:03
Closing this since nobody seems to know how to handle the "stripped" keyword, and how it fits in tha YAML specification.

**Closed by aaubry** 2016-08-30 23:03 UTC

**Comment by cyraid** [comment] 2023-05-06 09:33
@aaubry Is that not just the Anchor Value?

In https://yaml.org/spec/1.2.2/#692-node-anchors

> First occurrence: &anchor Value
> Second occurrence: *anchor

First is setting the anchor `&anchor` to `Value` and the second is using it, no? So in the case above for Unity, is `!u!4 &41387171 stripped` not just the local tag, followed by `&41387171` as the anchor name, and `stripped` as the value for the Anchor?
