### ISSUE TITLE
Getting odd hash values in keys

### ISSUE THREAD

**Issue by gregsdennis** [aaubry/YamlDotNet#809] opened 2023-05-30 05:04 UTC
**Describe the bug**
The output of writing a `YamlDocument` to a string is generating weird hash values in repeated keys and values.  Only the last occurrence doesn't have the hash.

**To Reproduce**
```c#
var yamlDoc = new YamlDocument(
    new YamlMappingNode(
        new KeyValuePair<YamlNode, YamlNode>(
            "rootProp1",
            new YamlMappingNode(new KeyValuePair<YamlNode, YamlNode>("simpleValue", "string"))
        ),
        new KeyValuePair<YamlNode, YamlNode>(
            "rootProp2",
            new YamlMappingNode(new KeyValuePair<YamlNode, YamlNode>("simpleValue", "string"))
        )
    )
);

var newYamlStream = new YamlStream(yamlDoc);
var buffer = new StringBuilder();
using var writer = new StringWriter(buffer);
newYamlStream.Save(writer);

var newYamlText = writer.ToString();

Console.WriteLine(newYamlText);
```

outputs

```
rootProp1:
  &1073701529 simpleValue: &1477267762 string
rootProp2:
  simpleValue: string
...
```

You can see the odd values before the first `simpleValue` key and before the `string` value on line 2 of the output.  The odd value changes every time, which leads me to believe it's the `.GetHashCode()` value.  I have no idea why it's included.

I imagine the system is trying to save memory by not storing the same keys again.  That's fine, but that shouldn't affect output.

**Comment by gregsdennis** [comment] 2023-05-31 21:37
Workaround:

```c#
var serializer = new SerializerBuilder().Build();
return serializer.Serialize(yamlDoc.RootNode);
```

**Comment by EdwardCooke** [comment] 2023-06-02 03:56
It’s actually a random value used as an anchor to point to another spot in the yaml to reduce the size of the resulting yaml.

**Comment by EdwardCooke** [comment] 2023-06-17 14:43
I'm going to close this since it's by design with a valid work around and fully supported by the yaml spec .

**Closed by EdwardCooke** 2023-06-17 14:43 UTC

**Comment by gregsdennis** [comment] 2023-06-17 22:50
@EdwardCooke can you explain how this is valid per the spec?  It doesn't look like it produces valid YAML.

**Comment by EdwardCooke** [comment] 2023-06-17 23:13
Here’s from the reference parser. You can make some really weird looking yaml that’s still valid. 

http://ben-kiki.org/ypaste/data/77649/index.html
