### ISSUE TITLE
Serializer ignores ISerializable objects.

### ISSUE THREAD

**Issue by PoroCYon** [aaubry/YamlDotNet#129] opened 2015-04-10 14:45 UTC
When serizalizing an object that implements `ISerializable`, `GetObjectData` is never called, thus ignoring the implementation.

EDIT: I have written an `IYamlTypeConverter` to do that, but ReadYaml is never called.

``` csharp
public struct ISerializableConverter : IYamlTypeConverter
{
    readonly static string
        TYPE  = "type" ,
        VALUE = "value",

        TYPE_NOT_ISABLE = "type does not implement System.Runtime.Serialization.ISerializable." ,
        VAL_NOT_ISABLE  = "value does not implement System.Runtime.Serialization.ISerializable.";

    public bool Accepts(Type type)
    {
        return Array.IndexOf(type.GetInterfaces(), typeof(ISerializable)) != -1;
    }

    public object ReadYaml(IParser parser, Type type)
    {
        // somehow, it's never called
        throw new Exception("meep");

        // I hope this works (untestable)
        if (!Accepts(type))
            throw new ArgumentException(TYPE_NOT_ISABLE, TYPE, null);

        dynamic ret = Activator.CreateInstance(type);

        var r = new EventReader(parser);

        r.Expect<MappingStart>();

        while (r.Accept<Scalar>())
            ret[r.Expect<Scalar>()] = r.Expect<Scalar>();

        r.Expect<MappingEnd>();

        return ret;
    }
    public void WriteYaml(IEmitter emitter, object value, Type type)
    {
        if (!Accepts(type))
            throw new ArgumentException(TYPE_NOT_ISABLE, TYPE, null);

        if (value == null)
            throw new ArgumentNullException(VALUE);
        if (!Accepts(value.GetType())) // types always directly implement interfaces, even when not explicitely set at compile-time.
            throw new ArgumentException(VAL_NOT_ISABLE, VALUE, null);

        var s = (ISerializable)value;
        var si = new SerializationInfo(value.GetType(), new SystemFormatterConverter() /* simply a wrapper around System.Convert */);

        s.GetObjectData(si, new StreamingContext(StreamingContextStates.All));

        emitter.Emit(new MappingStart());
        foreach (SerializationEntry e in si)
        {
            emitter.Emit(new Scalar(e.Name));
            emitter.Emit(new Scalar(e.Value.ToString()));
        }
        emitter.Emit(new MappingEnd());
    }
}
```

**Comment by solvingJ** [comment] 2017-04-30 08:59
I just discovered that ISerializable is not called myself and then discovered this ticket. 

@aaubry Did you look at respecting ISerializable and using GetObjectData to return the list of properties?  I think I might be able to make a PR for this if not, although at first glance I could not figure out what source file it belongs in.  Any tips?

Here is the background on ISerializable, Json.NET does seem to honor it:
https://msdn.microsoft.com/en-us/library/system.runtime.serialization.iserializable(v=vs.110).aspx

**Comment by aaubry** [comment] 2017-05-02 22:03
There is no support for `ISerializable` because that interface it is tightly coupled with the built-in .NET serialization mechanism. You could probably write a converter similar to [`GuidConverter`](https://github.com/aaubry/YamlDotNet/blob/master/YamlDotNet/Serialization/Converters/GuidConverter.cs) and register it builders, but you will probably cause unexpected behavior since there are some "basic" types such as `System.DateTime` that implement `ISerializable`.

**Comment by solvingJ** [comment] 2017-05-03 14:47
It's coming back into .net core 2 and .net standard 2 because it is such an integral part of the framework that so many people relied on and designed around.  It's really hard to take a bunch of classes that already implement ISerializable which works for XML and JSON, and then go back and retrofit the applications with custom serialization to format XYZ like Bson, Yaml, protobuf... etc etc.   

As a result, I would like to officially request adding support for ISerializable in the future.  Since you mentioned limited availability for the project, would you consider a pull request if it's based on the new standards?

**Comment by aaubry** [comment] 2019-09-25 23:35
I'm sorry I was unable to answer this question in a timely fashion. Pull requests are always welcome, but as I imagine that you have certainly moved on to other things, I will close this issue, but feel free to reopen it if necessary.

**Closed by aaubry** 2019-09-25 23:35 UTC
Labels: enhancement
